# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://gfxnerd.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Scarlett Smiderle's Portfolio
# Description of the Site
description: Game Programmer Specializing in Core Gameplay, Tools, and Game AI.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Scarlett,Smiderle, Scarlett Smiderle, Portfolio, Game Programmer
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: angie.smiderle@gmail.com
linkedin_username: asmiderle
github_username:  Promethaes
itchio_username: Promethaes

# commented out cause i dont want random internet goers knowing my phone number
# resume: /assets/resume.pdf

# Google Analytics
google-analytics: UA-163806439-1

# Name of the Author
author-name: Scarlett Smiderle
# URL for the Image of the Author
author-image: /assets/images/me.jpg
# 60 Words About the Author
author-about: Hi there! I'm a Game Programmer specializing in Core Gameplay, Automation Tools, and Game AI. Check out my work on this site! Feel free to contact me, my resume is available upon request. Some hobbies include playing games (obviously!), espresso, being in nature and music.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Promethaes

resume: /assets/resume.pdf

#Project Card & Blog Post related
pc-icon-size: 3
pc-text-size: 6

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
